FROM gcr.io/kaniko-project/executor:latest

# ADD https://github.com/docker-library/busybox/raw/50b2c75ecc4c23c4ec47f3a4a0a2fd82002a1a33/stable/uclibc/busybox.tar.xz /bb

# COPY kaniko-runner.sh /kaniko-runner.sh
# COPY run_in_container.sh /src/run_in_container.sh
# COPY target.Dockerfile /src/Dockerfile

# ENTRYPOINT ["/bb/bin/sh","-c"]
# CMD ["/kaniko-runner.sh"]
